premAI-io/prem-utils

.github/workflows/publish.yaml
pyproject.toml

publish package

---

e2e.py
prem_utils/connectors/azure.py
prem_utils/connectors/cloudflare.py
prem_utils/connectors/cohere.py
prem_utils/connectors/lamini.py
prem_utils/connectors/mistral.py
prem_utils/connectors/replicate.py
prem_utils/models.json

Embeddings

---

prem_utils/models.json

- New OpenAI models 
- Deprecate OctoAI models and added codellama-70b

Updated Models

---

prem_utils/connectors/azure.py
prem_utils/connectors/cloudflare.py
prem_utils/connectors/cohere.py
prem_utils/connectors/lamini.py
prem_utils/connectors/mistral.py
prem_utils/connectors/openai.py
prem_utils/connectors/replicate.py

Fixed embeddings schema to align with OpenAI specifics.

Fix embeddings schema

---

prem_utils/models.json

Closes #40 
Added new cloudflare models into `models.json`

added cloudflare models

---

prem_utils/__init__.py
prem_utils/utils.py

Closes #42 
```python
from prem_utils import get_models_data
print(get_models_data()) # { "connectors" : [...] }
```

Added top-level function get_models_data()

---

e2e.py
prem_utils/connectors/deepinfra.py
prem_utils/connectors/openai.py
prem_utils/connectors/prem.py
prem_utils/models.json

This PR:
- Adds DeepInfra connector class
- And removes deepinfra dependency on openai

Deepinfra connector class

---

prem_utils/connectors/prem.py

This PR adds removes all the models, which are not served by Modal.

Keeping only the models served with Modal. 

---

requirements.txt

Update openai and tiktoken packages

---

prem_utils/connectors/prem.py

Added Prem Finetuning

---

prem_utils/models.json

Part of #25 
Added the following embeddings models:
- embed-english-light-v3.0
- embed-multilingual-v3.0
- embed-multilingual-light-v3.0

Added some cohere embeddings models (Embed-v3)

---

prem_utils/models.json

Added flag `finetuning` for fine-tunable models only. Overall, only 6 models are fine-tunable:

Added flag 'finetuning' 

---

prem_utils/connectors/anyscale.py

bugfix in anyscale tool choice

---

prem_utils/models.json

add command r plus

---

prem_utils/models.json

Parameter Spec

---

prem_utils/models.json

Deprecate pplx models

---

prem_utils/models.json

deprecated opus model

---

prem_utils/models.json

Reverts premAI-io/prem-utils#118

Revert "deprecated opus model"

---

prem_utils/models.json

added alias to embedding models

---

prem_utils/connectors/prem.py
prem_utils/models.json

update models.json file for prem_1b_chat support

Support for prem_1b_chat
